print('Classificador de coisas')
a = input('Digite algo:')
print('O tipo primitivo desse valor é:', type(a))
print('Se tem espaços?', a.isspace())
print('É alfabeto?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Está em maiúscula?', a.isupper())
print('Está em minúscula?', a.islower())
print('Está capitalizada?', a.istitle())