print('Ache a posição da letra')
x = str(input('Digite uma frase:')).strip().upper()
x1 = str(x.count('A'))
print(f'A letra A aparece {x1} vezes na frase')
x2 = x.find('A')
print(f'A letra A aparece pela primeira vez na posição {x2}')
x3 = x.rfind('A')
print(f'A letra A aparece pela última vez na posição {x3}')