x = str(input("Digite seu nome: "))
separa = x.split()
print(f"Seu nome em maiúsculas é {x.upper()}")
print(f"Seu nome em minúsculas é {x.lower()}")
print(f"Seu nome ao todo tem {len(x) - x.count(' ')} letras")
print(f"Seu primeiro nome é {separa[0]} com {len(separa[0])} letras")